// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKmUF9Fi1ozXK_VmbamZ85o2Csi-UNhug',
    appId: '1:696359566510:web:473ffd7c7f4a99f265c13f',
    messagingSenderId: '696359566510',
    projectId: 'simpleinsta',
    authDomain: 'simpleinsta.firebaseapp.com',
    storageBucket: 'simpleinsta.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpvLmKR-PRCV5HLJjoIqinClLSBddTxhU',
    appId: '1:696359566510:android:c54d97d28cec5a7865c13f',
    messagingSenderId: '696359566510',
    projectId: 'simpleinsta',
    storageBucket: 'simpleinsta.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIrhunnMQyWfky2lxMLh2BQ3R2cu8bVIw',
    appId: '1:696359566510:ios:ba5887457cf4532565c13f',
    messagingSenderId: '696359566510',
    projectId: 'simpleinsta',
    storageBucket: 'simpleinsta.appspot.com',
    iosClientId: '696359566510-pc0r2pknop2tht6pt5g9g41is6fot2ul.apps.googleusercontent.com',
    iosBundleId: 'com.example.instaclone',
  );
}
